services:
  microservice1:
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  microservice2:
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development